config:
  partial_parse: False
  use_colors: True
  printer_width: 120
  send_anonymous_usage_stats: False

my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: momentumcc.us-east-1

      user: "{{ var('SNOWFLAKE_USERNAME', 'fivetran_vivek') }}"
      # Keypair config
      private_key_path: "{{ var('SNOWFLAKE_PRIVATE_KEY_PATH', '.keys/fivetran_vivek.p8') }}" 
      private_key_passphrase: "{{ env_var('SNOWFLAKE_KEY_PASSPHRASE') }}"

      database: "{{ var('SNOWFLAKE_DATABASE', 'FIVETRAN_SALESFORCE') }}"
      warehouse: "{{ var('SNOWFLAKE_WAREHOUSE', 'ETLRESEARCH_SMALL_NCLFOLKS') }}"
      schema: CRM_SALESFORCE
      threads: "{{ var('SNOWFLAKE_THREADS', 1) }}"
      client_session_keep_alive: False

